apiVersion: v1
kind: Namespace
metadata:
  name: go_service-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go_service-pod
  namespace: go_service-system
spec:
  selector:
    matchLabels:
      app: go_service
  template:
    metadata:
      labels:
        app: go_service
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: go_service
        image: go-service-amd64:1.0.0-alpha
        