apiVersion: k3d.io/v1alpha4 
kind: Simple 

metadata:
  name: local 

servers: 1 
agents: 1  

image: rancher/k3s:v1.22.7-k3s1

registries: 
  create: 
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"

options:
  k3d: 
    wait: true

  kubeconfig:
    updateDefaultKubeconfig: true 
    switchCurrentContext: true


