apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/sales-system/
patchesStrategicMerge:
- ./sales-patch.yaml
images:
- name: sales-image
  newName: registry.kenobi.local:5000/sales-amd64
  newTag: 1.0.2-alpha
